/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCompteRouteImport } from './routes/_app/compte'
import { Route as AppManuscritsIdRouteImport } from './routes/_app/manuscrits.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCompteRoute = AppCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AppRoute,
} as any)
const AppManuscritsIdRoute = AppManuscritsIdRouteImport.update({
  id: '/manuscrits/$id',
  path: '/manuscrits/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/compte': typeof AppCompteRoute
  '/manuscrits/$id': typeof AppManuscritsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/compte': typeof AppCompteRoute
  '/': typeof AppIndexRoute
  '/manuscrits/$id': typeof AppManuscritsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/compte': typeof AppCompteRoute
  '/_app/': typeof AppIndexRoute
  '/_app/manuscrits/$id': typeof AppManuscritsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/admin' | '/compte' | '/manuscrits/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/admin' | '/compte' | '/' | '/manuscrits/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/compte'
    | '/_app/'
    | '/_app/manuscrits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compte': {
      id: '/_app/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AppCompteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manuscrits/$id': {
      id: '/_app/manuscrits/$id'
      path: '/manuscrits/$id'
      fullPath: '/manuscrits/$id'
      preLoaderRoute: typeof AppManuscritsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCompteRoute: typeof AppCompteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppManuscritsIdRoute: typeof AppManuscritsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCompteRoute: AppCompteRoute,
  AppIndexRoute: AppIndexRoute,
  AppManuscritsIdRoute: AppManuscritsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
